id: PAA3A698A
initial_creation_type: ocr
source_metadata:
  volumes:
    3467bb24c29b4cbc866b2547935704be:
      base_file: v039.txt
      image_group_id: I1PD95884
      title: སྒྲོལ་མའི་སྒྲུབ་ཐབས།
      total_pages: 1625
      volume_number: 39
